In [13]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [8]:
import numpy as np
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [12]:
import numpy as np
c=np.zeros((3,5))
print(c)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
d=np.random.random((3,2))
print(d)

[[0.15424017 0.76262958]
 [0.0086665  0.93074312]
 [0.99552792 0.48088009]]


In [17]:
e=np.arange(0,25,5)
print(e)

[ 0  5 10 15 20]
