In [1]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.hstack((arr1,arr2))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [2]:
result1=np.vstack((arr1,arr2))
print(result1)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [4]:
result2=np.dstack((arr1,arr2))
print(result2)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
