In [4]:
import numpy as np
g=np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])
h=g.reshape(4,3)
print("\nnormal three dimensional array:\n",g,"\nreshaped array:\n",h)


normal three dimensional array:
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]] 
reshaped array:
 [[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]


In [5]:
import numpy as np
g=np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])
i=g.flatten()
print("\nnormal three dimensional array:\n",g,"\nFlatten array:\n",i)


normal three dimensional array:
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]] 
Flatten array:
 [ 10  20  30  40  50  60  70  80  90 100 110 120]


In [6]:
import numpy as np
g=np.array([[[10,20,30,40],[50,60,70,80]],[[90,100,110,120],[130,140,150,160]]])
print("\nArray dimension:\n",g.ndim)


Array dimension:
 3


In [7]:
import numpy as np
c=np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])
print("Shape of the array:\n",c.shape)

Shape of the array:
 (3, 4)


In [8]:
import numpy as np
c=np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])
print("Datatype of the array:\n",c.dtype)

Datatype of the array:
 int64


In [9]:
import numpy as np
c=np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])
size=len(c)
print("size of the array:\n",size)

size of the array:
 3


In [10]:
import numpy as np
a=[1,2,3]
a=np.array(a)
newtype=a.astype('float64')
print(a)
print(newtype)
print(newtype.dtype)

[1 2 3]
[1. 2. 3.]
float64
